const BoardStatActionTypes = {
    INCREASE_INPUTTED_NUMBER: "INCREASE_INPUTTED_NUMBER",
    DECREASE_INPUTTED_NUMBER: "DECREASE_INPUTTED_NUMBER",
    INCREASE_SOLVED_NUMBER: "INCREASE_SOLVED_NUMBER",
    DECREASE_SOLVED_NUMBER: "DECREASE_SOLVED_NUMBER",
    INCREASE_LOGIC_ROUNDS: "INCREASE_LOGIC_ROUNDS",
    INCREASE_CHECK_FOR_GIVENS_ROUNDS: "INCREASE_CHECK_FOR_GIVENS_ROUNDS",
    ADD_BOX_TO_CHECK_FOR_GIVENS_ARRAY: "ADD_BOX_TO_CHECK_FOR_GIVENS_ARRAY",
    INCREASE_SLICING_ROUNDS: "INCREASE_SLICING_ROUNDS",
    ADD_BOX_TO_SLICED_ARRAY: "ADD_BOX_TO_SLICED_ARRAY",
};

export default BoardStatActionTypes;