const BoxErrorActionTypes = {
    ADD_ERROR_TO_BOX: "ADD_ERROR_TO_BOX",
    CLEAR_ERROR_FROM_BOX: "CLEAR_ERROR_FROM_BOX",
    CLEAR_ALL_ERRORS_FROM_BOX: "CLEAR_ALL_ERRORS_FROM_BOX",
    ADD_CONFLICT_TO_BOX: "ADD_CONFLICT_TO_BOX",
    CLEAR_HAS_CONFLICTS: "CLEAR_HAS_CONFLICTS",
    CLEAR_FROM_HAS_CONFLICTS: "CLEAR_FROM_HAS_CONFLICTS"
};

export default BoxErrorActionTypes;