const BoardActionTypes = {
    UPDATE_BOX_VALUE: "UPDATE_BOX_VALUE",
    VALIDATE_BOX_VALUE: "VALIDATE_BOX_VALUE",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    ADD_ERROR_TO_BOX: "ADD_ERROR_TO_BOX",
    CLEAR_ERROR_FROM_BOX: "CLEAR_ERROR_FROM_BOX",
    ADD_CONFLICT_TO_BOX: "ADD_CONFLICT_TO_BOX",
    CLEAR_HAS_CONFLICTS: "CLEAR_HAS_CONFLICTS",
    CLEAR_FROM_HAS_CONFLICTS: "CLEAR_FROM_HAS_CONFLICTS"
};

export default BoardActionTypes;